@startuml process-view-level2-uc00

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam style strictuml
hide unlinked

autonumber 1.1

participant "Data Gateway" as DG
participant "Data Store" as DS
participant "Data Processor Slave\nBackend" as SDP
participant "Data Decoder Slave\nBackend" as SDD
participant "Identity Management Slave\nBackend" as SIM
participant "Message Broker" as MB
participant "Data Validator\nBackend" as DVB
participant "Device Management Slave\nBackend" as DRSB
participant "Device Commander" as DC
participant "Fleet Management\nBackend" as LTB
participant "Smart Irrigation\nBackend" as SIB

activate MB

DS -> MB :   subscribe to X data
SDP -> MB :  subscribe to new\nX decoded sensor data
SDP -> MB :  subscribe to changes\n in transformations
SDD -> MB :  subscribe to new\nX encoded sensor data
SDD -> MB :  subscribe to changes\n in decoders
DVB -> MB :  subscribe to new\nprocessed sensor data
SIM -> MB :  subscribe to new\nprocessed and validated sensor data
SIM -> MB :  subscribe to changes\n in devices identity
DRSB -> MB : subscribe to new\ngps sensor data validated
DRSB -> MB : subscribe to changes\n in device management
DC -> MB : subscribe to device commands
LTB -> MB :  subscribe to new validated\ngps sensor data\nwith device info
SIB -> MB :  subscribe to new validated\ngps+trigger sensor data\n with device info
SIB -> MB :  subscribe to new validated\ngps+temperature+air humidity\n sensor data with device info
SIB -> MB :  subscribe to new validated\ngps+soil moisture+illuminance\n sensor data with device info

@enduml
