SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS decoder;

CREATE DATABASE decoder WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE decoder OWNER TO "user";

\connect decoder

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA public OWNER TO "user";

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.decoder (
    persistence_id bigint NOT NULL,
    device_type character varying(255),
    script text
);


ALTER TABLE public.decoder OWNER TO "user";

ALTER TABLE public.decoder ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.decoder_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.decoder_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.decoder
    ADD CONSTRAINT decoder_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.decoder
    ADD CONSTRAINT uk_koot74cxq1h6st293ywiot3lp UNIQUE (device_type);
