SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS records;

CREATE DATABASE records WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE records OWNER TO "user";

\connect records

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA public OWNER TO "user";

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.record (
    persistence_id bigint NOT NULL,
    device_id character varying(255),
    name character varying(255)
);

ALTER TABLE public.record OWNER TO "user";

CREATE TABLE public.record_entries (
    record_persistence_id bigint NOT NULL,
    entries_persistence_id bigint NOT NULL
);

ALTER TABLE public.record_entries OWNER TO "user";

CREATE TABLE public.record_entry (
    persistence_id bigint NOT NULL,
    content character varying(255),
    label character varying(255),
    type integer NOT NULL
);

ALTER TABLE public.record_entry OWNER TO "user";

ALTER TABLE public.record_entry ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_entry_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.record ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.record_entry_persistence_id_seq', 1, false);

SELECT pg_catalog.setval('public.record_persistence_id_seq', 1, false);

ALTER TABLE ONLY public.record_entries
    ADD CONSTRAINT record_entries_pkey PRIMARY KEY (record_persistence_id, entries_persistence_id);

ALTER TABLE ONLY public.record_entry
    ADD CONSTRAINT record_entry_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.record_entries
    ADD CONSTRAINT uk_5bdw8mcgn5hgioqa9mmbyd33x UNIQUE (entries_persistence_id);

ALTER TABLE ONLY public.record
    ADD CONSTRAINT uk_n4ua98wwd1g1fniw0tmsphahv UNIQUE (device_id);

ALTER TABLE ONLY public.record_entries
    ADD CONSTRAINT fkc3qtnjilw43wm8jnnhrdeitah FOREIGN KEY (record_persistence_id) REFERENCES public.record(persistence_id);

ALTER TABLE ONLY public.record_entries
    ADD CONSTRAINT fkpd2pg96emce9mp0go2bg0wh2v FOREIGN KEY (entries_persistence_id) REFERENCES public.record_entry(persistence_id);
