version: "3.7"
services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672
      - 15672:15672
  sharespot-lgt92-gps-data-gateway:
    build: backend-services/sharespot-lgt92-gps-data-gateway
    image: sharespot-lgt92-gps-data-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-gateway.env
    networks:
      - sharespot-network
    ports:
      - 8081:8080
  sharespot-data-relayer:
    build: backend-services/sharespot-data-relayer
    image: sharespot-data-relayer
    networks:
      - sharespot-network
    ports:
      - 8080:80
  sharespot-location-tracking-backend:
    build: backend-services/sharespot-location-tracking-backend
    image: sharespot-location-tracking-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-location-tracking-backend.env
    networks:
      - sharespot-network
    ports:
      - 8084:8080
  sharespot-lgt92-gps-data-processor:
    build: backend-services/sharespot-lgt92-gps-data-processor
    image: sharespot-lgt92-gps-data-processor
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-processor.env
    networks:
      - sharespot-network
    ports:
      - 8082:8080
  sharespot-device-records-slave-backend:
    build: backend-services/sharespot-device-records-slave-backend
    image: sharespot-device-records-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8085:8080
  sharespot-device-records-master-backend:
    build: backend-services/sharespot-device-records-master-backend
    image: sharespot-device-records-master-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8083:8080
  sharespot-device-records-database:
    build: databases/sharespot-device-records-database
    image: sharespot-device-records-database
    container_name: sharespot-device-records-database
    env_file:
      - ./secrets/prod/sharespot-device-records-database.env
    networks:
      - sharespot-network
    ports:
      - 5432:5432
    volumes:
      - ./databases-data/dev/sharespot-device-records-database:/var/lib/postgresql/data/
  sharespot-fast-data-store:
    build: backend-services/sharespot-fast-data-store
    image: sharespot-fast-data-store
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-fast-data-store-backend.env
    networks:
      - sharespot-network
    ports:
      - 8086:8080
  questdb:
    image: questdb/questdb
    container_name: questdb
    networks:
      - sharespot-network
    ports:
      - 8812:8812
      - 9000:9000
      - 9003:9003
    volumes:
      - ./databases-data/dev/questdb:/root/.questdb/
  sharespot-data-store:
    build: backend-services/sharespot-data-store
    image: sharespot-data-store
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-store-backend.env
    networks:
      - sharespot-network
    ports:
      - 8087:8080
  sharespot-data-store-database:
    image: mongo:latest
    container_name: sharespot-data-store-database
    env_file:
      - ./secrets/prod/sharespot-data-store-database.env
    networks:
      - sharespot-network
    ports:
      - 27017:27017
    volumes:
      - ./databases-data/dev/sharespot-data-store-database:/data/db
      - ./secrets/prod/init-sharespot-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  sharespot-network: {}
