services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672:5672
      - 15672:15672
  sharespot-data-relayer:
    build: backend-services/sharespot-data-relayer
    image: sharespot-data-relayer
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 8443:443
  sharespot-data-gateway:
    build: backend-services/sharespot-data-gateway
    image: sharespot-data-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-gateway.env
    networks:
      - sharespot-network
    ports:
      - 8079:8080
  sharespot-data-processor-slave-backend:
    build: backend-services/sharespot-data-processor-slave-backend
    image: sharespot-data-processor-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-processor-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8082:8080
  sharespot-data-processor-master-backend:
    build: backend-services/sharespot-data-processor-master-backend
    image: sharespot-data-processor-master-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-processor-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8083:8080
  sharespot-device-records-slave-backend:
    build: backend-services/sharespot-device-records-slave-backend
    image: sharespot-device-records-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8084:8080
  sharespot-data-validator-backend:
    build: backend-services/sharespot-data-validator-backend
    image: sharespot-data-validator-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-validator-backend.env
    networks:
      - sharespot-network
    ports:
      - 8095:8080
  sharespot-device-records-master-backend:
    build: backend-services/sharespot-device-records-master-backend
    image: sharespot-device-records-master-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8085:8080
  sharespot-fleet-management-backend:
    build: backend-services/sharespot-fleet-management-backend
    image: sharespot-fleet-management-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-fleet-management-backend.env
    networks:
      - sharespot-network
    ports:
      - 8086:8080
  smart-irrigation-backend:
    build: backend-services/smart-irrigation-backend
    container_name: smart-irrigation-backend
    image: smart-irrigation-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/smart-irrigation-backend.env
    networks:
      - sharespot-network
    ports:
      - 8098:8080
  sharespot-identity-management-backend:
    build: backend-services/sharespot-identity-management-backend
    image: sharespot-identity-management-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-identity-management-backend.env
    networks:
      - sharespot-network
    ports:
      - 8090:8080
  sharespot-identity-management-slave-backend:
    build: backend-services/sharespot-identity-management-slave-backend
    image: sharespot-identity-management-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-identity-management-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8091:8080
  sharespot-data-decoder-master-backend:
    build: backend-services/sharespot-data-decoder-master-backend
    image: sharespot-data-decoder-master-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-decoder-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8092:8080
  sharespot-data-decoder-slave-backend:
    build: backend-services/sharespot-data-decoder-slave-backend
    image: sharespot-data-decoder-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-decoder-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8093:8080
  sharespot-common-database:
    build: databases/sharespot-common-database
    image: sharespot-common-database
    container_name: sharespot-common-database
    env_file:
      - ./secrets/prod/sharespot-common-database.env
    networks:
      - sharespot-network
    ports:
      - 5432:5432
    volumes:
      - ./databases-data/prod/sharespot-common-database:/var/lib/postgresql/data/
  questdb:
    image: questdb/questdb:6.2
    container_name: questdb
    networks:
      - sharespot-network
    ports:
      - 8812:8812
      - 9000:9000
      - 9003:9003
    volumes:
      - ./databases-data/prod/questdb:/root/.questdb/
  irrigation-database:
    image: questdb/questdb:6.2
    container_name: irrigation-database
    networks:
      - sharespot-network
    ports:
      - 8898:8812
      - 9098:9000
      - 9003
    volumes:
      - ./databases-data/prod/irrigation-database:/root/.questdb/
  # sharespot-data-store:
  #   build: backend-services/sharespot-data-store
  #   image: sharespot-data-store
  #   environment:
  #     spring_profiles_active: prod
  #   env_file:
  #     - ./secrets/prod/sharespot-data-store-backend.env
  #   networks:
  #     - sharespot-network
  #   ports:
  #     - 8087:8080
  # sharespot-data-store-database:
  #   image: mongo:latest
  #   container_name: sharespot-data-store-database
  #   env_file:
  #     - ./secrets/prod/sharespot-data-store-database.env
  #   networks:
  #     - sharespot-network
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./databases-data/prod/sharespot-data-store-database:/data/db
  #     - ./secrets/prod/init-sharespot-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  sharespot-network:
