version: "3.7"
services:
  data-relayer:
    build: backend-services/data-relayer
    image: data-relayer
    ports:
      - 8080:80
    networks:
      - sharespot-network
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672
      - 15672:15672
  sharespot-lgt92-gps-sensor-gateway:
    restart: on-failure
    build: backend-services/lgt92-gps-sensor-gateway
    image: sharespot-lgt92-gps-sensor-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/lgt92-gps-sensor-gateway.env
    ports:
      - 8080
    networks:
      - sharespot-network
  sharespot-lgt92-gps-sensor-processor:
    restart: on-failure
    build: backend-services/lgt92-gps-sensor-processor
    image: sharespot-lgt92-gps-sensor-processor
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/lgt92-gps-sensor-processor.env
    ports:
      - 8080
    networks:
      - sharespot-network
  sharespot-location-tracking-backend:
    restart: on-failure
    build: backend-services/location-tracking-backend
    image: sharespot-location-tracking-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/location-tracking-backend.env
    ports:
      - 8080
    networks:
      - sharespot-network
  location-tracking-frontend:
    build: frontend
    image: location-tracking-frontend
    container_name: location-tracking-frontend
    networks:
      - sharespot-network
    ports:
      - 80:80
networks:
  sharespot-network:
