services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672
  sharespot-common-database:
    build: databases/sharespot-common-database
    image: sharespot-common-database
    container_name: sharespot-common-database
    env_file:
      - ./secrets/dev/sharespot-common-database.env
    ports:
      - 5432:5432
    volumes:
      - ./databases-data/prod/sharespot-common-database:/var/lib/postgresql/data/
  sharespot-data-store-database:
    image: mongo:latest
    container_name: sharespot-data-store-database
    ports:
      - 27017:27017
    volumes:
      - ./databases-data/prod/sharespot-data-store-database:/data/db
      - ./secrets/dev/init-sharespot-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./secrets/dev/sharespot-data-store-database.env
  questdb:
    image: questdb/questdb
    ports:
      - 8812:8812
      - 9000:9000
      - 9003:9003
    volumes:
      - ./databases-data/prod/questdb:/root/.questdb/
