services:
  message-broker:
    image: rabbitmq:3.10.5-management
    container_name: message-broker
    env_file:
      - secrets/dev/message-broker.env
    ports:
      - 5672:5672
      - 15672:15672
  sharespot-common-database:
    build: databases
    container_name: sharespot-common-database
    env_file:
      - ./secrets/prod/sharespot-common-database.env
    ports:
      - 5432:5432
    volumes:
      - ./databases-data/prod/sharespot-common-database:/var/lib/postgresql/data/
  questdb:
    image: questdb/questdb:6.3.1
    ports:
      - 8812:8812
      - 9000:9000
      - 9003
    volumes:
      - ./databases-data/prod/questdb:/root/.questdb/
  irrigation-database:
    image: questdb/questdb:6.3.1
    container_name: irrigation-database
    ports:
      - 8898:8812
      - 9098:9000
      - 9003
    volumes:
      - ./databases-data/prod/irrigation-database:/root/.questdb/
  # data-store-database:
  #   image: mongo:latest
  #   container_name: data-store-database
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./databases-data/prod/data-store-database:/data/db
  #     - ./secrets/dev/init-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   env_file:
  #     - ./secrets/dev/data-store-database.env
