services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672
      - 15672
  ui-aggregator:
    build:
      dockerfile: docker/ui-aggregator/Dockerfile
      context: frontend-services
    image: ui-aggregator
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 443:443
    depends_on:
      - sharespot-device-records-frontend
      - sharespot-data-processor-frontend
      - sharespot-fleet-management-frontend
  sharespot-device-records-frontend:
    build:
      dockerfile: docker/sharespot-device-records-frontend/Dockerfile
      context: frontend-services
    image: sharespot-device-records-frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 443
    depends_on:
      - sharespot-device-records-master-backend
  sharespot-data-processor-frontend:
    build:
      dockerfile: docker/sharespot-data-processor-frontend/Dockerfile
      context: frontend-services
    image: sharespot-data-processor-frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 443
    depends_on:
      - sharespot-data-processor-master-backend
  sharespot-fleet-management-frontend:
    build:
      dockerfile: docker/sharespot-fleet-management-frontend/Dockerfile
      context: frontend-services
    image: sharespot-fleet-management-frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 443
    depends_on:
      - sharespot-fleet-management-backend
  sharespot-data-relayer:
    build: backend-services/sharespot-data-relayer
    image: sharespot-data-relayer
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/nginx/ssl:/etc/nginx/ssl/
    networks:
      - sharespot-network
    ports:
      - 8443:443
  sharespot-data-gateway:
    build: backend-services/sharespot-data-gateway
    image: sharespot-data-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-gateway.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-processor-slave-backend:
    build: backend-services/sharespot-data-processor-slave-backend
    image: sharespot-data-processor-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-processor-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-processor-master-backend:
    build: backend-services/sharespot-data-processor-master-backend
    image: sharespot-data-processor-master-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-processor-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-device-records-slave-backend:
    build: backend-services/sharespot-device-records-slave-backend
    image: sharespot-device-records-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-slave-backend.env
    networks:
      - sharespot-network
  sharespot-device-records-master-backend:
    build: backend-services/sharespot-device-records-master-backend
    image: sharespot-device-records-master-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-validator-backend:
    build: backend-services/sharespot-data-validator-backend
    image: sharespot-data-validator-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-validator-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-fleet-management-backend:
    build: backend-services/sharespot-fleet-management-backend
    container_name: sharespot-fleet-management-backend
    image: sharespot-fleet-management-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-fleet-management-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-identity-management-backend:
    build: backend-services/sharespot-identity-management-backend
    container_name: sharespot-identity-management-backend
    image: sharespot-identity-management-backend
    volumes:
      - ./secrets/keys:/etc/ssh/app
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-identity-management-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080:8080
  sharespot-identity-management-slave-backend:
    build: backend-services/sharespot-identity-management-slave-backend
    container_name: sharespot-identity-management-slave-backend
    image: sharespot-identity-management-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-identity-management-slave-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-store:
    build: backend-services/sharespot-data-store
    image: sharespot-data-store
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-store-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-common-database:
    build: databases/sharespot-common-database
    image: sharespot-common-database
    container_name: sharespot-common-database
    env_file:
      - ./secrets/prod/sharespot-common-database.env
    networks:
      - sharespot-network
    ports:
      - 5432
    volumes:
      - ./databases-data/prod/sharespot-common-database:/var/lib/postgresql/data/
  questdb:
    image: questdb/questdb:6.2
    container_name: questdb
    networks:
      - sharespot-network
    ports:
      - 8812
      - 9000
      - 9003
    volumes:
      - ./databases-data/prod/questdb:/root/.questdb/
  sharespot-data-store-database:
    image: mongo:latest
    container_name: sharespot-data-store-database
    env_file:
      - ./secrets/prod/sharespot-data-store-database.env
    networks:
      - sharespot-network
    ports:
      - 27017
    volumes:
      - ./databases-data/prod/sharespot-data-store-database:/data/db
      - ./secrets/prod/init-sharespot-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  sharespot-network:
