version: "3.7"
services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672
      - 15672:15672
  ui-aggregator:
    build:
      dockerfile: docker/ui-aggregator/Dockerfile
      context: frontend-services
    image: ui-aggregator
    networks:
      - sharespot-network
    ports:
      - 80:80
  sharespot-device-records-frontend:
    build:
      dockerfile: docker/sharespot-device-records-frontend/Dockerfile
      context: frontend-services
    image: sharespot-device-records-frontend
    networks:
      - sharespot-network
    ports:
      - 80
  sharespot-location-tracking-frontend:
    build:
      dockerfile: docker/sharespot-location-tracking-frontend/Dockerfile
      context: frontend-services
    image: sharespot-location-tracking-frontend
    networks:
      - sharespot-network
    ports:
      - 80
  sharespot-lgt92-gps-data-gateway:
    build: backend-services/sharespot-lgt92-gps-data-gateway
    image: sharespot-lgt92-gps-data-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-gateway.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-relayer:
    build: backend-services/sharespot-data-relayer
    image: sharespot-data-relayer
    networks:
      - sharespot-network
    ports:
      - 8080:80
  sharespot-location-tracking-backend:
    build: backend-services/sharespot-location-tracking-backend
    container_name: sharespot-location-tracking-backend
    image: sharespot-location-tracking-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-location-tracking-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-lgt92-gps-data-processor:
    build: backend-services/sharespot-lgt92-gps-data-processor
    image: sharespot-lgt92-gps-data-processor
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-processor.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-device-records-database:
    build: databases/sharespot-device-records-database
    image: sharespot-device-records-database
    container_name: sharespot-device-records-database
    env_file:
      - ./secrets/prod/sharespot-device-records-database.env
    networks:
      - sharespot-network
    ports:
      - 5432
    volumes:
      - sharespot-device-records-database:/var/lib/postgresql/data/
  sharespot-device-records-backend:
    build: backend-services/sharespot-device-records-backend
    container_name: sharespot-device-records-backend
    image: sharespot-device-records-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
networks:
  sharespot-network: {}
volumes:
  sharespot-device-records-database:
    name: sharespot-device-records-database
