version: "3.7"
services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672
  sharespot-device-records-database:
    image: postgres:latest
    env_file:
      - ./secrets/dev/sharespot-device-records-database.env
    ports:
      - 5432:5432
    volumes:
      - ./databases-data/sharespot-device-records-database:/var/lib/postgresql/data/
  questdb:
    image: questdb/questdb
    ports:
      - 8812:8812
      - 9000:9000
      - 9003:9003
    volumes:
      - ./databases-data/questdb:/root/.questdb/
