version: "3.7"
services:
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    networks:
      - sharespot-network
    ports:
      - 5672
      - 15672:15672
  ui-aggregator:
    build:
      dockerfile: docker/ui-aggregator/Dockerfile
      context: frontend-services
    image: ui-aggregator
    networks:
      - sharespot-network
    ports:
      - 80:80
    depends_on:
      - sharespot-device-records-frontend
      - sharespot-location-tracking-frontend
  sharespot-device-records-frontend:
    build:
      dockerfile: docker/sharespot-device-records-frontend/Dockerfile
      context: frontend-services
    image: sharespot-device-records-frontend
    networks:
      - sharespot-network
    ports:
      - 80
    depends_on:
      - sharespot-device-records-master-backend
  sharespot-location-tracking-frontend:
    build:
      dockerfile: docker/sharespot-location-tracking-frontend/Dockerfile
      context: frontend-services
    image: sharespot-location-tracking-frontend
    networks:
      - sharespot-network
    ports:
      - 80
    depends_on:
      - sharespot-location-tracking-backend
  sharespot-lgt92-gps-data-gateway:
    build: backend-services/sharespot-lgt92-gps-data-gateway
    image: sharespot-lgt92-gps-data-gateway
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-gateway.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-data-relayer:
    build: backend-services/sharespot-data-relayer
    image: sharespot-data-relayer
    networks:
      - sharespot-network
    ports:
      - 8080:80
  sharespot-location-tracking-backend:
    build: backend-services/sharespot-location-tracking-backend
    container_name: sharespot-location-tracking-backend
    image: sharespot-location-tracking-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-location-tracking-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-lgt92-gps-data-processor:
    build: backend-services/sharespot-lgt92-gps-data-processor
    image: sharespot-lgt92-gps-data-processor
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-lgt92-gps-data-processor.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-device-records-database:
    build: databases/sharespot-device-records-database
    image: sharespot-device-records-database
    container_name: sharespot-device-records-database
    env_file:
      - ./secrets/prod/sharespot-device-records-database.env
    networks:
      - sharespot-network
    ports:
      - 5432
    volumes:
      - ./databases-data/prod/sharespot-device-records-database:/var/lib/postgresql/data/
  sharespot-device-records-slave-backend:
    build: backend-services/sharespot-device-records-slave-backend
    image: sharespot-device-records-slave-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-slave-backend.env
    networks:
      - sharespot-network
  sharespot-device-records-master-backend:
    build: backend-services/sharespot-device-records-master-backend
    image: sharespot-device-records-master-backend
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-device-records-master-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  sharespot-chrono-data-store:
    build: backend-services/sharespot-chrono-data-store
    image: sharespot-chrono-data-store
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-chrono-data-store-backend.env
    networks:
      - sharespot-network
    ports:
      - 8080
  questdb:
    image: questdb/questdb
    ports:
      - 8812
      - 9000
      - 9003
    volumes:
      - ./databases-data/prod/questdb:/root/.questdb/
  sharespot-data-store:
    build: backend-services/sharespot-data-store
    image: sharespot-data-store
    environment:
      spring_profiles_active: prod
    env_file:
      - ./secrets/prod/sharespot-data-store-backend.env
    networks:
      - sharespot-network
    ports:
      - 8087:8080
  sharespot-data-store-database:
    image: mongo:latest
    container_name: sharespot-data-store-database
    env_file:
      - ./secrets/prod/sharespot-data-store-database.env
    networks:
      - sharespot-network
    ports:
      - 27017:27017
    volumes:
      - ./databases-data/prod/sharespot-data-store-database:/data/db
      - ./secrets/prod/init-sharespot-data-store-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  sharespot-network:
