@startuml data-flow

skinparam Monochrome true

start
:any data received in\n**Data Relayer**;
:X data received in\n**Static\Dynamic Data Gateway**;
:X data processed in\n**Data Processor Slave Backend**;
:device records added to gps data in\n**Device Records Slave Backend**;
:gps data with records received in\n**Location Tracking Backend**;
:gps data with records received in\n**Location Tracking Frontend**;
end

@enduml
