@startuml logical-view-level3-lgt-92-gps-sensor-processor

skinparam Monochrome true

component "LGT 92 GPS Sensor Processor" {
    component "Application" as APP
    component "Infrastructure" as INFRA {
        component "Boot" as BOOT
        component "Mapper" as MAP
        component "Endpoint" as ENDPOINT {
            component "AMQP Egress" as EGRESS
            component "AMQP Ingress" as INGRESS
            interface "AMQP Egress API" as EGRESS_API
            interface "AMQP Ingress API" as INGRESS_API
        }
        () "Boot API" as BOOT_API
        () "Mapper API" as MAP_API
    }

    () "Application API" as APP_API

    EGRESS_API -- EGRESS
    INGRESS_API -- INGRESS

    APP_API -- APP
    BOOT_API -- BOOT
    MAP_API -- MAP

    EGRESS --( APP_API
    INGRESS --( APP_API

    MAP --( EGRESS_API
    MAP --( INGRESS_API

    BOOT --( MAP_API
    BOOT --( INGRESS_API
    BOOT --( EGRESS_API
}

@enduml
