@startuml logical-view-level3-location-tracking-backend

skinparam Monochrome true

component "Location Tracking Backend" {
    component "Domain" as D
    component "Application" as As
    component "Infrastructure" as IF {
        component "Boot" as Bt
        component "Endpoint" as EP {
            component "GraphQL" as RWS
            component "AMQP" as EL
        }
        () "Boot _API" as Bt_API
        () "GraphQL _API" as RWS_API
        () "AMQP _API" as EL_API
    }

    () "Domain _API" as D_API
    () "Application _API" as As_API

    D_API -- D
    As_API -- As
    Bt_API -- Bt
    EL_API -- EL
    RWS_API -- RWS

    As --( D_API
    IF --( As_API
    Bt --( RWS_API
    Bt --( EL_API
}

@enduml
