@startuml logical-view-level3-chrono-data-store

skinparam Monochrome true

component "Chrono Data Store" {
    component "Application" as APP
    component "Infrastructure" as INFRA {
        component "Boot" as BOOT
        component "Mapper" as MAP
        component "Presistence" as PERSIST {
            component "QuestDB" as QUEST
            interface "QuestDB API" as QUEST_API
        }
        component "Endpoint" as ENDPOINT {
            component "AMQP" as AMQP
            interface "AMQP API" as AMQP_API
        }
        interface "Boot API" as BOOT_API
        interface "Mapper API" as MAP_API
    }
    interface "Application API" as APP_API

    MAP_API -- MAP
    QUEST_API -- QUEST
    AMQP_API -- AMQP
    APP_API -- APP
    BOOT_API -- BOOT

    AMQP --( APP_API
    QUEST --( APP_API
    BOOT --( QUEST_API
    BOOT --( AMQP_API
    BOOT --( MAP_API

    MAP --( AMQP_API
    MAP --( QUEST_API
}

@enduml
