@startuml logical-view-level2

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

interface "UI" as UI

interface "Rest API" as IN_ENDPOINT

component "Environment" <<System>> {
    component "Message Broker" as MB <<Container>>
    component "Device Records Master Backend" as DRB <<Container>>
    component "Device Records Slave Backend" as DRSB <<Container>>
    component "Fleet Management Backend" as LTB <<Container>>
    component "Data Gateway" as DDG <<Container>>
    component "Data Relayer" as DR <<Container>>
    component "UI Aggregator" as UIAG <<Container>> {
        component "Device Records Frontend" as DRF <<Container>>
        component "Data Processor Frontend" as DPF <<Container>>
        component "Fleet Management Frontend" as LTF <<Container>>
        component "Simple Auth Frontend" as SAF <<Container>>
    }
    component "Data Processor Slave Backend" as DPSB <<Container>>
    component "Data Processor Master Backend" as DPMB <<Container>>
    component "Data Validator Backend" as DVB <<Container>>
    component "Device Records Database" as DRDB <<Container>>
    component "Data Processor Database" as DPDB <<Container>>
    component "Data Store" as DS <<Container>>
    component "QuestDB" as QUESTDB <<Container>>
    component "MongoDB" as MONGODB <<Container>>
    component "Simple Auth Backend" as SAB <<Container>>

    interface "Message Broker\nAPI" as MB_API
    interface "Fleet Management Backend\nAPI" as LTB_API
    interface "Device Records Master Backend\nAPI" as DRB_API
    interface "Data Processor Master Backend\nAPI" as DPMB_API
    interface "Device Records Database\nAPI" as DRDB_API
    interface "Data Processor Database\nAPI" as DPDB_API
    interface "QuestDB\nAPI" as QUESTDB_API
    interface "MongoDB\nAPI" as MONGODB_API
    interface "Data Gateway\nAPI" as DDG_API
    interface "Simple Auth\nAPI" as SAB_API

    LTB --( QUESTDB_API
    DS --( MONGODB_API
    DDG -- DDG_API
    DPMB_API -- DPMB
    DRB_API -- DRB
    MB_API -- MB
    DRDB_API -- DRDB
    DPDB_API -- DPDB
    LTB_API -- LTB
    SAB_API -- SAB
    UI -- UIAG
    MONGODB_API -- MONGODB
    QUESTDB_API -- QUESTDB
    DRB --( DRDB_API
    DRSB --( DRDB_API
    DPMB --( DPDB_API
    DPSB --( DPDB_API
    LTF --( LTB_API
    DPF --( DPMB_API
    DRF --( DRB_API
    SAF --( SAB_API

    DVB --( MB_API
    DS --( MB_API
    LTB --( MB_API
    DRB --( MB_API
    DPMB --( MB_API
    DRSB --( MB_API
    DPSB --( MB_API
    DDG --( MB_API

    DR -- IN_ENDPOINT
    DDG_API )-- DR
}

@enduml
