@startuml process-view-level2-uc01

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam style strictuml
hide unlinked

autonumber 1

participant "Data\nRealyer" as DG
participant "Data\nGateway" as SDDG
participant "Data Processor Slave\nBackend" as DPSB
participant "Device Records Slave\nBackend" as DRSB
participant "Message\nBroker" as MB
participant "Location Tracking\nBackend" as LTB
participant "Location Tracking\nFrontend" as LTF

activate MB
activate LTF

-> DG : new sensor data
activate DG

DG -> SDDG : new X type\nsensor data
activate SDDG

SDDG -> MB : publish event of new\nX type sensor data

DG <-- SDDG : OK
deactivate SDDG

<-- DG : OK
deactivate DG

MB -> DPSB : send event of new\nX sensor data
activate DPSB

DPSB -> MB : publish event of new\nprocessed sensor data
deactivate DPSB

MB -> DRSB : send event of new\nprocessed sensor data
activate DRSB

DRSB -> MB : new gps sensor data\nwith device records
deactivate DRSB

MB -> LTB : send event of new gps\nsensor data with records
activate LTB

LTB -> LTF : new gps sensor data\nwith device records
deactivate LTB
LTF -> LTF : present new gps sensor\ndata with device records

@enduml
