@startuml process-view-level2-uc00

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam style strictuml
hide unlinked

autonumber 1.1

participant "Data Gateway" as DG
participant "Data Store" as DS
participant "Chrono Data Store" as CDS
participant "Data Processor Slave\nBackend" as SDP
participant "Message Broker" as MB
participant "Location Tracking\nBackend" as LTB
participant "Device Records Slave\nBackend" as DRSB
participant "Location Tracking\nFrontend" as LTF
participant "Data Validator\nBackend" as DVB

activate MB
activate LTF
activate LTB

== Initialization ==
DS -> MB :   subscribe to X data
CDS -> MB :  subscribe to new\ngps sensor data with records
SDP -> MB :  subscribe to new\nX sensor data
SDP -> MB :  subscribe to changes\n in transformations
LTB -> MB :  subscribe to new\nvalidated gps sensor data with records
DRSB -> MB : subscribe to new\ngps sensor data validated
DRSB -> MB : subscribe to changes\n in device records
DVB -> MB :  subscribe to new\nprocessed sensor data
...
== UC01 Initialization ==
autonumber inc A
LTF <- : user acesses the UI
LTF -> LTB : fetch last location\n of each sensor
LTF -> LTB : subscribe to new\ngps sensor data
...
== UC02 Initialization ==
autonumber inc A
LTF <- : user wants to see\narray of gps sensor data
LTF -> LTB : unsubscribe from new\ngps sensor data
LTF -> LTB : subscribe to array of new\ngps sensor data

...
== UC01 Initialization ==
autonumber inc A
LTF <- : user wants to see\nall gps sensor data
LTF -> LTB : unsubscribe from array of new\ngps sensor data
LTF -> LTB : subscribe to new\ngps sensor data

@enduml
