@startuml logical-view-level2

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

interface "UI" as UI

interface "Sensae Console\nRest API" as IN_ENDPOINT
interface "Helium Console\nRest API" as OUT_ENDPOINT

interface "Azure Active Directory API" as AUTH_ENDPOINT

component "Environment" <<System>> {
    component "UI Aggregator" as UIAG <<Container>> {
        component "Fleet Management Frontend" as LTF <<Container>> 
        component "Smart Irrigation Frontend" as SIF <<Container>>
        component "Device Management Frontend" as DRF <<Container>>
        component "Data Processor Frontend" as DPF <<Container>>
        component "Data Decoder Frontend" as DDF <<Container>>
        component "Identity Management Frontend" as IAMF <<Container>>
    }
    component "Fleet Management Backend" as LTB <<Container>>
    component "Smart Irrigation Backend" as SIB <<Container>>
    component "Message Broker" as MB <<Container>>
    component "Device Management Master Backend" as DRB <<Container>>
    component "Device Management Slave Backend" as DRSB <<Container>>
    component "Data Gateway" as DDG <<Container>>
    component "Data Relayer" as DR <<Container>>
    component "Data Processor Slave Backend" as DPSB <<Container>>
    component "Data Processor Master Backend" as DPB <<Container>>
    component "Data Decoder Slave Backend" as DDSB <<Container>>
    component "Data Decoder Master Backend" as DDB <<Container>>
    component "Data Validator Backend" as DVB <<Container>>
    component "Device Management Database" as DRDB <<Container>>
    component "Data Processor Database" as DPDB <<Container>>
    component "Data Decoder Database" as DDDB <<Container>>
    component "Identity Management Database" as IAMDB <<Container>>
    component "Data Store" as DS <<Container>>
    component "Fleet Management Database" as QUESTDB <<Container>>
    component "Data Store Database" as MONGODB <<Container>>
    component "Smart Irrigation Data Database" as SIDDB <<Container>>
    component "Smart Irrigation Business Database" as SIBDB <<Container>>
    component "Identity Management Backend" as IAMB <<Container>>
    component "Identity Management Slave Backend" as IAMSB <<Container>>
    component "Device Commander Backend" as DCB <<Container>>

    interface "Message Broker\nAPI" as MB_API
    interface "Fleet Management Backend\nAPI" as LTB_API
    interface "Smart Irrigation Backend\nAPI" as SIB_API
    interface "Device Management Master Backend\nAPI" as DRB_API
    interface "Data Processor Master Backend\nAPI" as DPB_API
    interface "Data Decoder Master Backend\nAPI" as DDMB_API
    interface "Device Management\nDatabase API" as DRDB_API
    interface "Data Processor\nDatabase API" as DPDB_API
    interface "Data Decoder\nDatabase API" as DDDB_API
    interface "Identity Management\nDatabase API" as IAMDB_API
    interface "Fleet Management\nDatabase API" as QUESTDB_API
    interface "Data Store\nDatabase API" as MONGODB_API
    interface "Smart Irrigation Data\nDatabase API" as SIDDB_API
    interface "Smart Irrigation Business\nDatabase API" as SIBDB_API
    interface "Data Gateway\nAPI" as DDG_API
    interface "Identity Management Backend\nAPI" as IAMB_API

    LTB --( QUESTDB_API
    SIB --( SIDDB_API
    SIBDB_API )- SIB
    DS --( MONGODB_API
    DDG -- DDG_API
    DPB_API -- DPB
    DDMB_API -- DDB
    DRB_API -- DRB
    MB -- MB_API
    DRDB_API - DRDB
    DPDB_API - DPDB
    DDDB_API - DDDB
    IAMDB_API - IAMDB
    LTB_API -- LTB
    SIB_API -- SIB
    IAMB_API -- IAMB
    UI -- UIAG
    MONGODB_API - MONGODB
    QUESTDB_API - QUESTDB
    SIDDB_API - SIDDB
    SIBDB_API -- SIBDB
    DRB --( DRDB_API
    DRDB_API )-[hidden]- DRSB
    DPB --( DPDB_API
    DDB --( DDDB_API
    DPDB_API )-[hidden]- DPSB
    DDDB_API )-[hidden]- DDSB
    IAMB --( IAMDB_API
    IAMDB_API )-[hidden]- IAMSB
    LTF --( LTB_API
    SIF --( SIB_API
    DPF --( DPB_API
    DDF --( DDMB_API
    DRF --( DRB_API
    IAMF --( IAMB_API

    LTB ---( MB_API
    SIB ---( MB_API
    DRB ---( MB_API
    DPB ---( MB_API
    DDB ---( MB_API
    IAMB ---( MB_API
    MB_API )--- DS
    MB_API )--- DDG
    MB_API )--- DVB
    MB_API )--- DRSB
    MB_API )--- DPSB
    MB_API )--- DDSB
    MB_API )--- IAMSB
    MB_API )--- DCB

    DR -- IN_ENDPOINT
    DDG_API )-- DR
    DCB ----( OUT_ENDPOINT
    IAMF -- AUTH_ENDPOINT
    AUTH_ENDPOINT -- IAMB

    IAMB --[hidden]- IAMSB
    DRB --[hidden]- DRSB
    DDB --[hidden]- DDSB
    DPB --[hidden]- DPSB

    LTF -[hidden] DRF
    SIF -[hidden] LTF
    LTB -[hidden] DRB
    SIB -[hidden] LTB

    DRDB -[hidden] MB

}

@enduml
