@startuml logical-view-level1

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle


[System] as S
[Helium Console] as HC
[Azure Active Directory] as AAD

() "UI" as UI
() "Helium Console\nRest API" as OUT_ENDPOINT
() "Sensae Console\nRest API" as IN_ENDPOINT
note bottom: Console integration\nendpoint

() "AAD API" as AUTH_ENDPOINT

actor "Manager" as Client
actor "Tenant" as Tenant

Client --( UI
Tenant --( UI

UI -- S
S -- IN_ENDPOINT
HC - OUT_ENDPOINT
S - AUTH_ENDPOINT

IN_ENDPOINT )- HC
OUT_ENDPOINT )- S
AUTH_ENDPOINT )- AAD

@enduml
