@startuml logical-view-level1

left to right direction

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle

[System] as S
[Helium Console] as HC
[Azure Active Directory] as AAD
[Google Identity Platform] as GIP

[Twilio Paltform] as SMS
[Google Email Platform] as EMAIL

() "UI" as UI
() "Helium Console\nRest API" as OUT_ENDPOINT
() "Sensae Console\nRest API" as IN_ENDPOINT

() "AAD API" as AZURE_ENDPOINT
() "Google API" as GOOGLE_ENDPOINT

() "Twilio API" as SMS_ENDPOINT
() "Google Email SMTP API" as EMAIL_ENDPOINT

actor "Manager" as Client
actor "Tenant" as Tenant
actor "Anonymous User" as Anonymous

Client --( UI
Tenant --( UI
Anonymous --( UI

UI -- S
S - IN_ENDPOINT
OUT_ENDPOINT -- HC
S --( AZURE_ENDPOINT
S --( GOOGLE_ENDPOINT
S --( EMAIL_ENDPOINT
S --( SMS_ENDPOINT

IN_ENDPOINT )- HC
OUT_ENDPOINT )- S
AZURE_ENDPOINT - AAD
GOOGLE_ENDPOINT - GIP

SMS_ENDPOINT - SMS
EMAIL_ENDPOINT - EMAIL

@enduml
