@startuml logical-view-level1

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle


[System] as S
[Helium Console] as HC
[Azure Active Directory] as AAD

() "UI" as UI
() "Helium Console\nRest API" as IN_ENDPOINT
note top: Console integratoin\nendpoint

() "AAD API" as AUTH_ENDPOINT

actor "Data Admin" as Client

Client --( UI

UI -- S
IN_ENDPOINT - S
S - AUTH_ENDPOINT

HC -( IN_ENDPOINT
AUTH_ENDPOINT )- AAD

@enduml
