export enum PropertyName {
  DATA_ID = 'Data ID',
  DEVICE_ID = 'Device ID',
  DEVICE_NAME = 'Device Name',
  REPORTED_AT = 'Reported At (in milis)',
  LATITUDE = 'GPS - Latitude',
  LONGITUDE = 'GPS - Longitude',
  ALTITUDE = 'GPS - Altitude (in meters)',
  MOTION = 'Motion',
  VELOCITY = 'Velocity (in km/h)',
  AQI = 'Air Quality (in EAQI)',
  HUMIDITY = 'Humidity (in Grams/m3)',
  PRESSURE = 'Pressure (in hPa)',
  TEMPERATURE = 'Temperature (in celsius)',
  SOIL_MOISTURE = 'Soil Moisture (in percentage)',
  ILLUMINANCE = 'Illuminance (in lux)',
  BATTERY_PERCENTAGE = 'Battery (in percentage)',
  BATTERY_VOLTS = 'Battery (in Volts)',
  ALARM = 'Alarm (boolean value)',
  INVALID = 'Invalid',
}
