@startuml model

skinparam Monochrome true
skinparam Shadowing false
hide empty members

class Domain

class ParkSensor as "Park Sensor"

class StoveSensor as "Stove Sensor"

class Valve

class Garden as "Irrigation Zone"

class GardenName as "Name"

interface Device

class Area

class LedgerEntry

class Content

class Ownership

class OpenDate

class CloseDate

class Name

class Id
class Id2 as "Id"

class GPSPoint

class Record

class EntryContent

class EntryLabel

Area "1" -- "*" GPSPoint: has boundaries >
Garden "1" -- "1" Area: defined by >
Garden "1" -- "1" GardenName: named >
Valve --|> Device : is
ParkSensor --|> Device : is
StoveSensor --|> Device : is
Device "1" -- "*" LedgerEntry: has info >
Device "1" -- "1" Id: has >
Garden "1" -- "1" Id2: has >
LedgerEntry "1" -- "1" OpenDate: has >
LedgerEntry "1" -- "0..1" CloseDate: has >
LedgerEntry "1" -- "1" Content: refer to >
LedgerEntry "1" -- "1" Ownership: belongs to >
Garden "1" -- "1" Ownership: belongs to >
Content "1" -- "*" Record: has >
Content "1" -- "1" Name: has >
Content "1" - "1" GPSPoint: has >
Ownership "1" -- "*" Domain: refers to >
Record "1" -- "1" EntryContent: has >
Record "1" -- "1" EntryLabel: has >

@enduml
