SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS irrigation;

CREATE DATABASE irrigation WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE irrigation OWNER TO "user";

\connect irrigation

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA public OWNER TO "user";

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

---- devices ----

CREATE TABLE public.devices (
                                persistence_id bigint NOT NULL,
                                device_type character varying(255),
                                device_id character varying(255)
);

ALTER TABLE public.devices OWNER TO "user";

ALTER TABLE public.devices ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

SELECT pg_catalog.setval('public.devices_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_unique_id UNIQUE (device_id);

---- ledger_entries ----

CREATE TABLE public.ledger_entries (
                                       persistence_id bigint NOT NULL,
                                       device_id character varying(255),
                                       device_name character varying(255),
                                       open_at timestamp,
                                       close_at timestamp,
                                       latitude character  varying(255),
                                       longitude character  varying(255),
                                       altitude character  varying(255),
                                       ownership  text,
                                       remote_control boolean default false not null
);

ALTER TABLE public.ledger_entries OWNER TO "user";

ALTER TABLE public.ledger_entries ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_entries_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

SELECT pg_catalog.setval('public.ledger_entries_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT ledger_entries_pkey PRIMARY KEY (persistence_id);

---- records ----

CREATE TABLE public.records (
                                persistence_id bigint NOT NULL,
                                entry_persistence_id bigint,
                                label character varying(255),
                                content character varying(255)
);

ALTER TABLE public.records OWNER TO "user";

ALTER TABLE public.records ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.records_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

SELECT pg_catalog.setval('public.records_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.records
    ADD CONSTRAINT records_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.records
    ADD CONSTRAINT records_entry_fkey FOREIGN KEY (entry_persistence_id) REFERENCES public.ledger_entries(persistence_id);

---- graden boundaries ----

CREATE TABLE public.gardening_area_boundary (
                                persistence_id bigint NOT NULL,
                                area_id character varying(255),
                                position smallint,
                                latitude character  varying(255),
                                longitude character  varying(255),
                                altitude character  varying(255)
);

ALTER TABLE public.gardening_area_boundary ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boundary_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
    
---- graden owners ----

CREATE TABLE public.gardening_area_owner (
                                persistence_id bigint NOT NULL,
                                area_id character varying(255),
                                domain_id character  varying(255)
);

ALTER TABLE public.gardening_area_owner ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.owner_garden_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

SELECT pg_catalog.setval('public.owner_garden_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.gardening_area_owner
    ADD CONSTRAINT owner_garden_persistence_id_seq PRIMARY KEY (persistence_id);

---- graden ----

CREATE TABLE public.gardening_area (
                                persistence_id bigint NOT NULL,
                                id character varying(255),
                                name character  varying(255)
);

ALTER TABLE public.gardening_area ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.garden_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

SELECT pg_catalog.setval('public.garden_persistence_id_seq', 1, true);

ALTER TABLE ONLY public.gardening_area
    ADD CONSTRAINT gardening_area_pkey PRIMARY KEY (persistence_id);

