SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS transformations;

CREATE DATABASE transformations WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE transformations OWNER TO "user";

\connect transformations

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA public OWNER TO "user";

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.property_transformation (
    persistence_id bigint NOT NULL,
    value integer NOT NULL,
    old_path character varying(255),
    transformation_persistence_id bigint
);

ALTER TABLE public.property_transformation OWNER TO "user";

ALTER TABLE public.property_transformation ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_transformation_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transformation (
    persistence_id bigint NOT NULL,
    device_type character varying(255)
);

ALTER TABLE public.transformation OWNER TO "user";

ALTER TABLE public.transformation ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transformation_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.property_transformation_persistence_id_seq', 16, true);

SELECT pg_catalog.setval('public.transformation_persistence_id_seq', 5, true);

ALTER TABLE ONLY public.property_transformation
    ADD CONSTRAINT property_transformation_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.transformation
    ADD CONSTRAINT transformation_pkey PRIMARY KEY (persistence_id);

ALTER TABLE ONLY public.transformation
    ADD CONSTRAINT uk_effwmiutsj1f4nuj67nppsh9u UNIQUE (device_type);

ALTER TABLE ONLY public.property_transformation
    ADD CONSTRAINT fkhw3sur1rsvkqciqga1ap4xrfv FOREIGN KEY (transformation_persistence_id) REFERENCES public.transformation(persistence_id);
