--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1 (Debian 14.1-1.pgdg110+1)
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS records;
--
-- Name: records; Type: DATABASE; Schema: -; Owner: user
--

CREATE DATABASE records WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE records OWNER TO "user";

\connect records

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: command_entry; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.command_entry (
    persistence_id bigint NOT NULL,
    id character varying(255),
    name character varying(255),
    payload character varying(255),
    port integer,
    sub_device_ref integer,
    device_persistence_id bigint
);


ALTER TABLE public.command_entry OWNER TO "user";

--
-- Name: command_entry_persistence_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.command_entry ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.command_entry_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: record; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.record (
    persistence_id bigint NOT NULL,
    device_id character varying(255),
    name character varying(255),
    downlink character varying(255)
);


ALTER TABLE public.record OWNER TO "user";

--
-- Name: record_entry; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.record_entry (
    persistence_id bigint NOT NULL,
    content character varying(255),
    label character varying(255),
    type integer NOT NULL,
    records_persistence_id bigint
);


ALTER TABLE public.record_entry OWNER TO "user";

--
-- Name: record_entry_persistence_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.record_entry ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_entry_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: record_persistence_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.record ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: sub_device; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.sub_device (
    persistence_id bigint NOT NULL,
    sub_device_id character varying(255),
    sub_device_ref integer,
    controller_persistence_id bigint
);


ALTER TABLE public.sub_device OWNER TO "user";

--
-- Name: sub_device_persistence_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.sub_device ALTER COLUMN persistence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_device_persistence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);

--
-- Name: command_entry command_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.command_entry
    ADD CONSTRAINT command_entry_pkey PRIMARY KEY (persistence_id);


--
-- Name: record_entry record_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.record_entry
    ADD CONSTRAINT record_entry_pkey PRIMARY KEY (persistence_id);


--
-- Name: record record_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_pkey PRIMARY KEY (persistence_id);


--
-- Name: sub_device sub_device_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sub_device
    ADD CONSTRAINT sub_device_pkey PRIMARY KEY (persistence_id);


--
-- Name: record uk_n4ua98wwd1g1fniw0tmsphahv; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT uk_n4ua98wwd1g1fniw0tmsphahv UNIQUE (device_id);


--
-- Name: sub_device_id_unique; Type: INDEX; Schema: public; Owner: user
--

CREATE UNIQUE INDEX sub_device_id_unique ON public.sub_device USING btree (sub_device_id);


--
-- Name: sub_device fkb5jue3wr2i0hqpqxkxn2dp4o9; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sub_device
    ADD CONSTRAINT fkb5jue3wr2i0hqpqxkxn2dp4o9 FOREIGN KEY (controller_persistence_id) REFERENCES public.record(persistence_id);


--
-- Name: record_entry fkhx7afiwgpywevsidf53nmwu68; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.record_entry
    ADD CONSTRAINT fkhx7afiwgpywevsidf53nmwu68 FOREIGN KEY (records_persistence_id) REFERENCES public.record(persistence_id);


--
-- Name: command_entry fkpndga0aud7vg8f22uvoetkqt1; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.command_entry
    ADD CONSTRAINT fkpndga0aud7vg8f22uvoetkqt1 FOREIGN KEY (device_persistence_id) REFERENCES public.record(persistence_id);


--
-- PostgreSQL database dump complete
--

