name: Sensae Console - Continuous Integration - Test changes

on:
  push:
    branches:
      - master
      - dev
      - "*"
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Set up Node 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test Suite
        run: ./project/scripts/run-tests.sh
